name: Apache Tomcat
description: |
  Tomcat Webserver
version: 8.0.36
category: Webserver
maintainer: "Patrick Wiener <patrick.wiener@hs-karlsruhe.de>"
minimum_rancher_version: v0.59.0
license:
projectURL: # A URL related to the catalog entry
