---
  zookeeper_version: "3.4.8"
  zookeeper_url: "http://ftp.halifax.rwth-aachen.de/apache/zookeeper/zookeeper-{{ zookeeper_version }}/zookeeper-{{ zookeeper_version }}.tar.gz"
  zookeeper_register_path_env: true

  apt_cache_timeout: 3600
  data_dir: /var/lib/zookeeper
  log_dir: /var/log/zookeeper
  client_port: 2181
  init_limit: 5
  sync_limit: 2
  tick_time: 2000
  zookeeper_dir: /opt/zookeeper-{{ zookeeper_version }}
  zookeeper_hosts:
    - "{{ inventory_hostname }}" # current machine
