version: '2'
services:

  jobmanager:
    image: biggis/flink:1.3.0
    hostname: jobmanager
    ports:
      - "8081:8081"
      - "6123:6123"
    command: docker-entrypoint.sh jobmanager
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager
      USER_ID: 1000
      USER_NAME: flink

  taskmanager:
    image: biggis/flink:1.3.0
    hostname: taskmanager
    depends_on:
      - jobmanager
    command: docker-entrypoint.sh taskmanager
    labels:
      io.rancher.scheduler.affinity:container_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.scheduler.global: 'true'
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager
      USER_ID: 1000
      USER_NAME: flink
