# tasks file for Java 8
# installation process according to
# http://www.2daygeek.com/install-oracle-java-7-8-on-centos-rhel-fedora-opensuse/
---
  # Java version related variables
  # specifies {{ jdk_version }} according to ../default/main.yml
  - include: java-role-variables.yml

  # Install libselinux-python if SELinux is enabled
  - name: Install libselinux-python binary for Ansible to work
    yum: name=libselinux-python state=present

  # Copy script for Java version check
  - name: Copy script to server
    copy: src="../files/java-version.sh"  dest="{{ build_directory }}/"  mode="a+x"

  # Check Java version
  - name: Check if specific version of Oracle JDK is installed
    shell: LC_ALL="en_US.UTF-8"  {{ build_directory }}/java-version.sh  "{{ jdk_version }}"
    register: jdk_info
    changed_when: false
    failed_when: jdk_info.rc > 0

  # Download Oracle JRE 8
  - name: Download Oracle JRE
    get_url:
      url: "{{ jdk_tarball_url }}.rpm"
      dest: "{{ build_directory }}/{{ jdk_tarball_file }}.rpm"
      headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    when: (jdk_info.stdout|from_json).not_found

  # Install Java
  - name: Install Java RPM file
    yum:
      name: "{{ build_directory }}/{{ jdk_tarball_file }}.rpm"
      state: present
    when: (jdk_info.stdout|from_json).not_found

  # Set Java version as default
  - name: Set Java version as default
    alternatives:
      name: "{{ item.exe }}"
      link: "/usr/bin/{{ item.exe }}"
      path: "{{ item.path }}/{{ item.exe }}"
    with_items:
      - { path: "{{ oracle_java_home }}/jre/bin", exe: 'java' }
      - { path: "{{ oracle_java_home }}/jre/bin", exe: 'keytool' }
      - { path: "{{ oracle_java_home }}/bin", exe: 'javac' }
      - { path: "{{ oracle_java_home }}/bin", exe: 'javadoc' }
    when: (jdk_info.stdout|from_json).not_found

  # Set JAVA_HOME in bash_profile
  - name: Set JAVA_HOME in bash_profile
    script: ../files/export-java-home-redhat.sh "{{ jdk_version }}" "{{ build_user }}"
    register: java_home
    changed_when: false
    failed_when: java_home.rc > 0
