name: BigGIS
description: |
  (Experimental) BigGIS Cluster
version: 0.3
category:
maintainer: "Patrick Wiener <patrick.wiener@hs-karlsruhe.de>"
minimum_rancher_version: v0.59.0
license: MIT
projectURL: # A URL related to the catalog entry
