version: '2'
services:

  tomcat:
    image: biggis/tomcat:8.0.36
    hostname: tomcat
    ports:
      - "8080:8080"
    labels:
      io.rancher.scheduler.affinity:host_label_ne: rancher.instance_type=server-agent
    environment:
      USER_ID: 1000
      USER_NAME: tomcat
      TOMCAT_ADMIN: ${admin_user}
      TOMCAT_ADMIN_PASSWORD: ${admin_password}
