---
  build_user: "{{ ansible_ssh_user }}"
  build_user_group: "{{ ansible_ssh_user }}"
  build_directory: /home/{{ build_user }}/sources
  yum_repo_path: "/etc/yum.repos.d"

  epel_release:
    "4": 10
    "5": 4
    "6": 8
    "7": 7

  epel_repo_url: "http://download.fedoraproject.org/pub/epel/{{ ansible_distribution_major_version }}/{{ ansible_userspace_architecture }}{{ '/' if ansible_distribution_major_version < '7' else '/e/' }}epel-release-{{ ansible_distribution_major_version }}-{{ epel_release[ansible_distribution_major_version] }}.noarch.rpm"
