---
  - name: Restart mesos-master
    service: name=mesos-master state=restarted

  - name: Restart mesos-slave
    service: name=mesos-slave state=restarted

  # While waiting for https://github.com/ansible/ansible-modules-core/issues/191
  - name: Reload daemon
    command: systemctl daemon-reload
