version: '2'
services:

  jobmanager:
    image: biggis/flink:1.2.0
    hostname: jobmanager
    ports:
      - "8081:8081"
      - "6123:6123"
    command: docker-entrypoint.sh jobmanager
    environment:
      USER_ID: 1000
      USER_NAME: flink
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  taskmanager:
    image: biggis/flink:1.2.0
    hostname: taskmanager
    depends_on:
      - jobmanager
    command: docker-entrypoint.sh taskmanager
    labels:
      io.rancher.scheduler.affinity:container_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    environment:
      USER_ID: 1000
      USER_NAME: flink
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  zookeeper:
    image: biggis/zookeeper:3.4.9
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      USER_ID: 1000
      USER_NAME: zookeeper
    volumes:
      - zookeeper-data:/tmp/zookeeper/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  kafka:
    image: biggis/kafka:0.10.1.1
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      #KAFKA_ADVERTISED_HOST_NAME: localhost
      USER_ID: 1000
      USER_NAME: kafka
    volumes:
      - kafka-data:/tmp/kafka/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

volumes:
  zookeeper-data:
    driver: rancher-nfs
    external: true
  kafka-data:
    driver: rancher-nfs
    external: true
