name: Apache Flink
description: |
  Flink cluster
version: 1.3.0
category: Stream Processing
maintainer: "Patrick Wiener <patrick.wiener@hs-karlsruhe.de>"
minimum_rancher_version: v0.59.0
license:
projectURL: # A URL related to the catalog entry
