---
  build_user: "{{ ansible_ssh_user }}"
  build_directory: /home/{{ build_user }}/sources
  virtualbox_version: 5.0
  virtualbox_rpm_package: VirtualBox-{{ virtualbox_version }}
  virtualbox_repo_url: "http://download.virtualbox.org/virtualbox/rpm/rhel/virtualbox.repo"
  yum_repo_path: "/etc/yum.repos.d"

  epel_release:
    "4": 10
    "5": 4
    "6": 8
    "7": 5

  epel_repo_url: "http://download.fedoraproject.org/pub/epel/{{ ansible_distribution_major_version }}/{{ ansible_userspace_architecture }}{{ '/' if ansible_distribution_major_version < '7' else '/e/' }}epel-release-{{ ansible_distribution_major_version }}-{{ epel_release[ansible_distribution_major_version] }}.noarch.rpm"
  # epel_repo_gpg_key_path: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
  epel_path: "{{ build_directory }}/epel-release-{{ ansible_distribution_major_version }}-{{ epel_release[ansible_distribution_major_version] }}.noarch.rpm"
